name: Acción de Autohospedado
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    steps:
      #- name: Checkout del repositorio
      # uses: actions/checkout@v2

      # Agrega aquí los pasos adicionales que deseas realizar en tu acción
      # Puedes ejecutar comandos, construir, probar, desplegar, etc.
      - name: Obtener número de líneas en program.cs
        run: |
          $url = "https://raw.githubusercontent.com/AnthonyMonsalve/NetFrameworkTest/master/Program.cs"
          $response = Invoke-WebRequest -Uri $url -UseBasicParsing
          $content = $response.Content
          
          # Aquí puedes realizar las operaciones que necesites con el contenido de la respuesta
          # Por ejemplo, contar las líneas en el archivo
          $line_count = ($content -split '\r?\n').Count
          Write-Host "El numero de lineas en program.cs es: $line_count"
      - name: Crear archivo
        run: |
          $url = "https://raw.githubusercontent.com/AnthonyMonsalve/NetFrameworkTest/master/Program.cs"
          $response = Invoke-WebRequest -Uri $url -UseBasicParsing
          $content = $response.Content
          
          # Aquí puedes realizar las operaciones que necesites con el contenido de la respuesta
          # Por ejemplo, contar las líneas en el archivo
          $line_count = ($content -split '\r?\n').Count
          $filePath = "C:\actions-runner\count-lines-$line_count.txt"
          $content = "El archivo Program.cs tiene $line_count lineas"
          
          if (Test-Path $filePath) {
              Set-Content -Path $filePath -Value $content
          } else {
              New-Item -ItemType File -Path $filePath -Value $content
          }
      - name: Hacer git clone
        run: |
          cd C:\Users\Administrador\Documents
          git clone https://github.com/AnthonyMonsalve/NetFrameworkTest.git






          #Invoke-WebRequest -Uri "https://raw.githubusercontent.com/AnthonyMonsalve/NetFrameworkTest/master/Program.cs" -OutFile "C:\Users\Administrador\Documents"

          # Ruta y nombre del archivo de texto
          #$archivo = "$env:USERPROFILE\count_lines.txt"
          # Escribir el contenido en el archivo
          #Set-Content -Path $archivo -Value $line_count
          
          
          # Contenido del archivo
          #$contenido = "El numero de lineas en program.cs es: $line_count"
          
          # Abrir una ventana de CMD con un mensaje
          #$cmdProcess = Start-Process cmd.exe -ArgumentList "/k echo El numero de lineas en program.cs es: $line_count" -PassThru
          
          # Esperar 10 segundos
          #Start-Sleep -Seconds 10
          
          # Cerrar la ventana de CMD
          #$cmdProcess.CloseMainWindow()



